/** Ejemplos opacos para placeholders de formularios y modales */
export const EX = {
  sku: "Ej. FIL-ACE-01",
  productName: "Ej. Filtro de aceite Premium",
  productDesc: "Ej. Compatible con motor 1.6L, incluye junta",
  presentation: "Ej. 1 litro, caja x12",
  vehicleCompat: "Ej. Nissan Versa 2015–2020",
  salePrice: "Ej. 189.99",
  purchasePrice: "Ej. 120.50",
  stockQty: "Ej. 24",
  minStock: "Ej. 5",
  categoryName: "Ej. Filtros de aceite",
  categorySlug: "Ej. filtros-aceite",
  brandName: "Ej. Bosch",
  brandSlug: "Ej. bosch",
  supplierName: "Ej. Autopartes del Golfo",
  supplierContact: "Ej. María López",
  supplierEmail: "Ej. ventas@proveedor.com",
  supplierPhone: "Ej. 229 123 4567",
  supplierAddress: "Ej. Av. Industrial 120, Veracruz",
  supplierNotes: "Ej. Entrega martes y viernes",
  employeeName: "Ej. Juan Pérez García",
  employeeEmail: "Ej. cajero@fortino.com",
  employeePassword: "Ej. Temp2026!",
  mediaName: "Ej. Filtro aceite frontal",
  mediaTags: "Ej. motor, aceite, filtros",
  purchaseRef: "Ej. FAC-20451",
  purchaseNotes: "Ej. Entrega parcial, pendiente 2 piezas",
  purchaseQty: "Ej. 10",
  purchaseCost: "Ej. 85.00",
  adjustQty: "Ej. 5",
  adjustStock: "Ej. 48",
  adjustNote: "Ej. Llegada del proveedor",
  cashMovementNote: "Ej. Pago renta del local",
  cashAmount: "Ej. 500.00",
  checkoutAmount: "Ej. 350.00",
  loginEmail: "Ej. admin@fortino.com",
  searchProduct: "Ej. SKU o nombre de pieza…",
  searchMedia: "Ej. frenos, aceite…",
} as const;
